// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDujzWuUNFAmwEVkYLAoXYeUWdOpe0w9ZM',
    appId: '1:437241531792:web:6c549312408b0f07647715',
    messagingSenderId: '437241531792',
    projectId: 'chatting-app-528d7',
    authDomain: 'chatting-app-528d7.firebaseapp.com',
    storageBucket: 'chatting-app-528d7.appspot.com',
    measurementId: 'G-QZ38JVFC0B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz7juXS1WLlVWgp6tZKuEkobSGUnd5F6k',
    appId: '1:437241531792:android:ce21e6d653ab6b91647715',
    messagingSenderId: '437241531792',
    projectId: 'chatting-app-528d7',
    storageBucket: 'chatting-app-528d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIu-6NDAq2ycKDum3B1KTMJ4C2keuIPx4',
    appId: '1:437241531792:ios:2e24d25e4ab2e304647715',
    messagingSenderId: '437241531792',
    projectId: 'chatting-app-528d7',
    storageBucket: 'chatting-app-528d7.appspot.com',
    iosBundleId: 'com.example.a1b2c3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8_lrX7iZDlbaiJQJhy2cDMT5q02sSwLs',
    appId: '1:464253847772:ios:f0d31df964059d61fe4c19',
    messagingSenderId: '464253847772',
    projectId: 'shoppingui-dd46a',
    storageBucket: 'shoppingui-dd46a.appspot.com',
    iosBundleId: 'com.example.a1b2c3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDujzWuUNFAmwEVkYLAoXYeUWdOpe0w9ZM',
    appId: '1:437241531792:web:1721ce27557af05f647715',
    messagingSenderId: '437241531792',
    projectId: 'chatting-app-528d7',
    authDomain: 'chatting-app-528d7.firebaseapp.com',
    storageBucket: 'chatting-app-528d7.appspot.com',
    measurementId: 'G-D5DKC7DREJ',
  );

}